name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout репозитория
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Установка Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      # 3. Установка зависимостей
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff pytest pytest-cov

      - name: Install package
        run: pip install .

      # 4. Установка CodeClimate Test Reporter
      - name: Install CodeClimate Test Reporter
        run: curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
      - name: Set permissions for test reporter
        run: chmod +x ./cc-test-reporter

      # 5. Подготовка тестового репортера
      - name: Before build
        run: ./cc-test-reporter before-build
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}

      # 6. Запуск линтера
      - name: Run lint
        run: make lint

      # 7. Запуск тестов с покрытием кода
      - name: Run tests
        run: pytest --cov=gendiff --cov-report=xml tests/

      # 8. Отправка покрытия кода
      - name: After build
        run: ./cc-test-reporter after-build --exit-code $?
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
